apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
resources:
  requests:
      cpu: 200m
      memory: 50Mi
  limits:
      cpu: 600m
      memory: 100Mi